#Return something from a 4 digit seed
validate <- function(ID4) {

if(!is.numeric(ID4))
  stop("You must use a 4 digit number")

words <- c("the",
           "be",
           "to",
           "of",
           "and",
           "a",
           "in",
           "that",
           "have",
           "I",
           "it",
           "for",
           "not",
           "on",
           "with",
           "he",
           "as",
           "you",
           "do",
           "at",
           "this",
           "but",
           "his",
           "by",
           "from",
           "they",
           "we",
           "say",
           "her",
           "she",
           "or",
           "an",
           "will",
           "my",
           "one",
           "all",
           "would",
           "there",
           "their",
           "what",
           "so",
           "up",
           "out",
           "if",
           "about",
           "who",
           "get",
           "which",
           "go",
           "me",
           "when",
           "make",
           "can",
           "like",
           "time",
           "no",
           "just",
           "him",
           "know",
           "take",
           "people",
           "into",
           "year",
           "your",
           "good",
           "some",
           "could",
           "them",
           "see",
           "other",
           "than",
           "then",
           "now",
           "look",
           "only",
           "come",
           "its",
           "over",
           "think",
           "also",
           "back",
           "after",
           "use",
           "two",
           "how",
           "our",
           "work",
           "first",
           "well",
           "way",
           "even",
           "new",
           "want",
           "because",
           "any",
           "these",
           "give",
           "day",
           "most",
           "us")

set.seed(ID4)
lst <- sample(words,5)

reply <- paste('Words for ', ID4, ':',lst[1], lst[2], lst[3], lst[4], lst[5])

}





